baseURL = "https://bkunzang.github.io/"
languageCode = "en-us"
title = "Brian Kunzang"
theme = "PaperMod"

relativeURLs = false
canonifyURLs = true

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  author = "Brian Kunzang"
  description = "A personal blog about me and my projects"
  keywords = ["Blog", "Personal", "Hugo"]
  showHomeRecentPosts = true      # enables recent posts on homepage
  homeRecentPostsTitle = "Recent Posts"
  homeRecentPostsLimit = 5       # number of posts to display

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 3


